(function () {

    // http://stackoverflow.com/a/2880929/1478566
    var urlParams = {};
    (function () {
        var match,
            pl     = /\+/g,  // Regex for replacing addition symbol with a space
            search = /([^&=]+)=?([^&]*)/g,
            decode = function (s) { return decodeURIComponent(s.replace(pl, " ")); },
            query  = window.location.search.substring(1);
        while (match = search.exec(query))
            urlParams[decode(match[1])] = decode(match[2]);
    })();

    var __tt_lang = 'en';
    var __tt_en = {};
    var __tt_ru = {
        'OK': 'OK',
        'Cancel': 'Отмена',
        'Up': 'Вверх',
        'Down': 'Вниз',
        'Backspace': 'Бекспейс',
        'Del': 'Удалить',
        'Layer': 'Слой',
        'animals': 'животные',
        'Invalid value given': 'Неверное значение дано',
        'No content to fit to': 'Нет содержания для подгонки',
        'There is already a layer named that!': 'Существует уже слой с именем, что!',
        'Please enter a unique layer name': 'Пожалуйста, введите уникальное имя слоя',
        'Please enter the new layer name': 'Пожалуйста, введите новое имя слоя',
        'Layer already has that name': 'Слой уже имеет это имя',
        'Move selected elements to layer "%s"?': 'Переместить выбранные элементы в слой "%s"?',
        '<strong>Do you want to clear the drawing?</strong>\nThis will also erase your undo history': '<strong>Вы хотите, чтобы очистить рисунок?</strong>\nЭто также сотрет вашу историю отмены?',
        'Do you want to open a new file?\nThis will also erase your undo history': 'Вы хотите, чтобы открыть новый файл?\nЭто также сотрет историю отмены?',
        'There were parsing errors in your SVG source.\nRevert back to original SVG source?': 'Там были разбора ошибок в исходном SVG.\nОткат обратно к первоначальному источнику SVG?',
        'Ignore changes made to SVG source?': 'Игнорировать изменения, внесенные в источник SVG?',
        'Feature not supported': 'Функция не поддерживается',
        'Enter the new image URL': 'Введите новый URL изображения',
        'NOTE: Due to a bug in your browser, this image may appear wrong (missing gradients or elements). It will however appear correct once actually saved.': 'Примечание: Из-за ошибки в вашем браузере, то этот образ может появиться неправильные (недостающие градиенты или элементы). Это, однако, будет отображаться правильно когда-то на самом деле сохранен.',
        'Loading image, please wait...': 'Загрузка изображений, пожалуйста, подождите ...',
        'Select "Save As..." in your browser to save this image as a "%s" file.': 'Выберите "Сохранить как ..." в вашем браузере, чтобы сохранить это изображение в виде файла "%s".',
        'Also note the following issues:': 'Также обратите внимание на следующие вопросы:',
        'There are unsaved changes.': 'Есть несохраненные изменения.',
        'Enter the new hyperlink URL': 'Введите новый URL гиперссылки',
        'Error: Unable to load SVG data': 'Ошибка: Не удалось загрузить данные SVG',
        'Unable to load from URL': 'Невозможно загрузить из URL',
        'Retrieving "%s" ...': 'Получение "%s" ...',
        'Search cliparts...': 'Поиск клипарты ...',
        'About this Editor...': 'Об этом редакторе ...',
        'Keyboard Shortcuts...': 'Горячие клавиши...',
        'New Document': 'Новый документ',
        'Open SVG...': 'Открыть SVG ...',
        'Import Image...': 'Импорт изображения ...',
        'Save Image... ': 'Сохранить изображение...',
        'Export as PNG': 'Экспорт в PNG',
        'Edit': 'редактировать',
        'Undo': 'расстегивать',
        'Redo': 'переделывать',
        'Duplicate': 'дублировать',
        'Object': 'объект',
        'Group Elements': 'Группа элементов',
        'Ungroup Elements': 'Ungroup элементы',
        'Convert to Path': 'Преобразовать в путь',
        'Reorient path': 'Переориентировать путь',
        'View': 'Посмотреть',
        'View Rulers': 'Просмотр Линейки',
        'View Wireframe': 'Просмотр каркасные',
        'Snap to Grid': 'Привязки к сетке',
        'Source...': 'Источник...',
        'Canvas': 'холст',
        'Change canvas width': 'Изменить ширину холста',
        'Change canvas height': 'высота Изменить холст',
        'Change canvas color': 'Изменение цвета холста',
        'Color': 'цвет',
        'Sizes': 'Размеры',
        'Fit to Content': 'Fit к содержимому',
        'Custom': 'изготовленный на заказ',
        'Rectangle': 'Прямоугольник',
        'Change rectangle width': 'Изменить ширину прямоугольника',
        'Change rectangle height': 'высота Изменить прямоугольник',
        'Path': 'Дорожка',
        'Image': 'Образ',
        'Change X coordinate': 'Изменение координат X',
        'Change Y coordinate': 'Изменение Y координат',
        'Change image width': 'Изменить ширину изображения',
        'Width': 'Ширина',
        'Change image height': 'высота Изменить изображение',
        'Height': 'Высота',
        'Circle': 'Круг',
        'Center X': 'Центр X',
        'Center Point': 'Центр',
        'Change circle\'s cx coordinate': 'Изменить круг сх координат',
        'Center Y': 'Центр Y',
        'Change circle\'s cy coordinate': 'Изменение круга координат су',
        'Radius': 'Радиус',
        'Change circle\'s radius': 'Радиус окружности Изменить',
        'Ellipse': 'Эллипс',
        'Change ellipse\'s cx coordinate': 'Изменение эллипса сх координат',
        'Change ellipse\'s cy coordinate': 'Изменение координат Эллипс Cy',
        'Change ellipse\'s x radius': 'Изменить эллипсом х радиус',
        'Radius X': 'Радиус X',
        'Change ellipse\'s y radius': 'Изменить радиус эллипса у',
        'Radius Y': 'Радиус Y',
        'Line': 'Линия',
        'Change line\'s starting x coordinate': 'Изменить строку, начинающуюся координаты х',
        'Start X': 'Start X',
        'Change line\'s starting y coordinate': 'Изменить строку, начинающуюся у координат',
        'Start Y': 'Пуск Y',
        'Change line\'s ending x coordinate': 'Изменение строки окончание х координат',
        'End X': 'End X',
        'Change line\'s ending y coordinate': 'Изменение линии завершено координату',
        'End Y': 'Конец Y',
        'Text': 'Текст',
        'Change text x coordinate': 'Изменить текст х координат',
        'Change text y coordinate': 'Изменить текст координату',
        'Font': 'Шрифт',
        'Letter [F]': 'Буква [F]',
        'Change Font Family': 'Изменение Семейство шрифтов',
        'Arvo': 'Арво',
        'Courier': 'курьер',
        'Euphoria': 'Эйфория',
        'Georgia': 'Грузия',
        'Helvetica': 'Гельветика',
        'Junction': 'стык',
        'League Gothic': 'Лига Готические',
        'Oswald': 'Освальд',
        'Palatino': 'Палатино',
        'Trebuchet': 'Требучет',
        'Shadows Into Light': 'Тени в свет',
        'Simonetta': 'Симонетта',
        'Times': 'раз',
        'Bold Text [B]': 'Жирный [B]',
        'Italic Text [I]': 'Курсив [I]',
        'Change Font Size': 'Изменить размер шрифта',
        'Font Size': 'Размер шрифта',
        'Break link to reference element (make unique)': 'Перерыв ссылку на эталонный элемент (сделать уникальный)',
        'Break link reference': 'ссылка ссылка Перерыв',
        'Change groups\'s x coordinate': 'Изменение групп х координат',
        'Change groups\'s y coordinate': 'Изменить группы координате у',
        'Edit Path': 'Редактировать путь',
        'Change node\'s x coordinate': 'Изменить узел х координат',
        'Change node\'s y coordinate': 'Изменить узел координату',
        'Segment Type': 'Тип сегмента',
        'Change Segment type': 'Изменить тип сегмента',
        'Curve': 'кривая',
        'Straight': 'Прямо',
        'Link Control Points': 'Контрольные точки Link',
        'Linked Control Points': 'Связанные контрольные точки',
        'Adds a node': 'Добавляет узел',
        'Add Node': 'Добавить узел',
        'Delete Node': 'Удалить узел',
        'Open/close sub-path': 'Открытие / закрытие субтрассе',
        'Open Path': 'Открытый Путь',
        'Add sub-path': 'Добавить подпути',
        'Change rotation angle': 'Угол поворота Изменить',
        'Rotation': 'вращение',
        'Change selected item opacity': 'Изменение выбранного элемента непрозрачности',
        'Opacity': 'помутнение',
        'Change gaussian blur value': 'Изменение значения гауссова размытия',
        'Blur': 'пятно',
        'Change Rectangle Corner Radius': 'Изменение Rectangle Corner Radius',
        'Roundness': 'круглость',
        'Align': 'выравнивать',
        'Multiple Elements': 'Несколько элементов',
        'Align relative to ...': 'Выравнивание по отношению к ...',
        'Align to objects': 'Выровнять объекты',
        'Align to page': 'Выровнять страницу',
        'Align Left': 'Выровнять по левому краю',
        'Align Center': 'Выровнять по центру',
        'Align Right': 'Выровнять по правому краю',
        'Align Top': 'По верхнему краю',
        'Align Middle': 'Выровнять Средний',
        'Align Bottom': 'Выровнять по нижнему краю',
        'Stroke': 'Инсульт',
        'Change stroke': 'Изменение хода',
        'Stroke Width': 'Инсульт Ширина',
        'Stroke Dash': 'Инсульт тире',
        'Change stroke dash style': 'Изменить ход тире стиль',
        'Stroke Join': 'Инсульт Регистрация',
        'Stroke Cap': 'Инсульт Cap',
        'Select Tool [V]': 'Выберите инструмент [V]',
        'Pencil Tool [P]': 'Карандаш инструмент [P]',
        'Line Tool [L]': 'Line Tool [L]',
        'Square/Rect Tool [R]': 'Квадрат / Rect Инструмент [R]',
        'Ellipse/Circle Tool [C]': 'Эллипс / Круглый инструмент [C]',
        'Path Tool [P]': 'Путь инструмент [P]',
        'Text Tool [T]': 'Инструмент Текст [T]',
        'Zoom Tool [Z]': 'Инструмент Масштаб [Z]',
        'Switch stroke and fill colors [X]': 'Переключения хода и цвета заливки [X]',
        'Change fill color': 'Изменить цвет заливки',
        'Change stroke color': 'Изменение цвета инсульта',
        'Change zoom level': 'Уровень масштабирования Изменение',
        'Click to change fill color, shift-click to change stroke color': 'Нажмите, чтобы изменить цвет заливки, сдвиг кнопкой мыши, чтобы изменить цвет обводки',
        'Copy the contents of this box into a text editor, then save the file with a .svg extension.': 'Скопируйте содержимое этого окна в текстовый редактор, а затем сохранить файл с расширением .svg.',
        'Done': 'Готово',
        'Apply Changes': 'Применить изменения',
        'Pixels': 'Пиксели',
        'Centimeters': 'сантиметров',
        'Millimeters': 'миллиметры',
        'Inches': 'дюймов',
        'Points': 'Точки',
        'Picas': 'Пики',
        'Ems': 'Эмс',
        'Exs': 'ExS',
        'Cut': 'Порез',
        'Copy': 'копия',
        'Paste': 'Вставить',
        'Delete': 'Удалить',
        'Group': 'группа',
        'Ungroup': 'Разгруппировать',
        'Bring to Front': 'На передний план',
        'Bring Forward': 'выдвигать',
        'Send Backward': 'Переместить назад',
        'Send to Back': 'Отправить Назад',
        'Pick a Stroke Paint and Opacity': 'Выберите штриха и непрозрачности',
        'Pick a Fill Paint and Opacity': 'Выберите заливку Paint и Непрозрачность',
        'Angle:': 'Угол:',
        'Begin Stop': 'Начало Стоп',
        'Cancel And Revert To Original Color': 'Отменить и вернуться к первоначальному цвету',
        'Center stop': 'Центр остановки',
        'Click To Open Color Picker': 'Нажмите, чтобы открыть палитру цветов',
        'Click To Revert To Original Color': 'Нажмите, чтобы вернуться к первоначальному цвету',
        'Click to set Angle': 'Нажмите, чтобы установить угол',
        'Click to set Ellip': 'Нажмите, чтобы установить Значение круговой',
        'Click to set Opac': 'Нажмите, чтобы установить Opac',
        'Click to set radius': 'Нажмите, чтобы задать радиус',
        'Commit To This Color Selection': 'Зафиксировать в выбор цвета',
        'Container element must have an id attribute to maintain unique id strings for sub-elements': 'Контейнерный элемент должен иметь атрибут, чтобы сохранить уникальные строки идентификатор подэлементам',
        'Drag Markers To Pick A Color': 'Перетащите маркеры, чтобы выбрать цвет',
        'Drag markers to pick a paint': 'Перетащите маркеры, чтобы выбрать краску',
        'Ellip:': 'Значение круговой:',
        'Begin Point': 'Начало',
        'End Point': 'Конец',
        'End stop': 'Планое',
        'Enter A &ldquo;Alpha&rdquo; Value (#00-#ff)': 'Введите &ldquo; Альфа &rdquo; Значение (# 00- # FF)',
        'Enter A &ldquo;Alpha&rdquo; Value (0-100)': 'Введите &ldquo; Альфа &rdquo; Значение (0-100)',
        'Enter A &ldquo;Blue&rdquo; Value (0-255)': 'Введите &ldquo; Синий &rdquo; Значение (0-255)',
        'Enter A &ldquo;Green&rdquo; Value (0-255)': 'Введите &ldquo; Green &rdquo; Значение (0-255)',
        'Enter A &ldquo;Hex&rdquo; Color Value (#000000-#ffffff)': 'Введите &ldquo; Hex &rdquo; Значение цвета (# 000000- # FFFFFF)',
        'Enter A &ldquo;Hue&rdquo; Value (0-360&deg;)': 'Введите &ldquo; Hue &rdquo; Значение (0-360&deg;)',
        'Enter A &ldquo;Red&rdquo; Value (0-255)': 'Введите &ldquo; Red &rdquo; Значение (0-255)',
        'Enter A &ldquo;Saturation&rdquo; Value (0-100%)': 'Введите &ldquo; Насыщенность &rdquo; Значение (0-100%)',
        'Enter A &ldquo;Value&rdquo; Value (0-100%)': 'Введите &ldquo; Value &rdquo; Значение (0-100%)',
        'Enter ending x value between 0.0 and 1.0': 'Введите конечное значение х в диапазоне от 0,0 до 1,0',
        'Enter ending y value between 0.0 and 1.0': 'Введите конечное значение у между 0,0 и 1,0',
        'Enter starting x value between 0.0 and 1.0': 'Введите начальное значение х в диапазоне от 0,0 до 1,0',
        'Enter starting y value between 0.0 and 1.0': 'Введите начальное значение у между 0,0 и 1,0',
        'Enter x value between 0.0 and 1.0': 'Введите значение х в диапазоне от 0,0 до 1,0',
        'Enter y value between 0.0 and 1.0': 'Введите у значение в диапазоне от 0,0 до 1,0',
        'Focal Point': 'фокус',
        'Focus point': 'Точка фокусировки',
        'Invalid Mode': 'Неверный режим',
        'Match center:': 'Матч-центр:',
        'New Color - Press &ldquo;OK&rdquo; To Commit': 'Новый цвет - Нажмите &ldquo; OK &rdquo; Для фиксации',
        'Opac:': 'Опасити:',
        'Pad': 'подушечка',
        'Pick the start color and opacity for the gradient': 'Выберите цвет начала и непрозрачность для градиента',
        'Radius:': 'Радиус:',
        'Reflect': 'отражать',
        'Repeat': 'Повторение',
        'Set To &ldquo;Alpha&rdquo; Color Mode': 'Установить &ldquo;Альфа&rdquo; Цветовой режим',
        'Set To &ldquo;Blue&rdquo; Color Mode': 'Установить &ldquo;Синий&rdquo; Цветовой режим',
        'Set To &ldquo;Green&rdquo; Color Mode': 'Установить &ldquo;Green&rdquo; Цветовой режим',
        'Set To &ldquo;Hue&rdquo; Color Mode': 'Установить &ldquo;Hue&rdquo; Цветовой режим',
        'Set To &ldquo;Red&rdquo; Color Mode': 'Установить &ldquo;Red&rdquo; Цветовой режим',
        'Set To &ldquo;Saturation&rdquo; Color Mode': 'Установить &ldquo;Насыщенность&rdquo; Цветовой режим',
        'Set To &ldquo;Value&rdquo; Color Mode': 'Установить &ldquo;Value&rdquo; Цветовой режим',
        'Solid': 'Однород.',
        'Linear': 'Лин.',
        'Radial': 'Круг.',
        'Spread method': 'метод Спред',
        'current color': 'текущий цвет',
        'new color': 'новый цвет'
    };

    var __tt;

    switch (String(urlParams['l'])) {
    case 'ru':
        __tt_lang = 'ru';
        __tt = __tt_ru;
        break;
    default:
        __tt_lang = 'en';
        __tt = __tt_en;
        break;
    }

    window.tt = function (text) {
        if (typeof __tt[text] == 'undefined') {
            return text;
        }
        return __tt[text];
    };

    window.tt.lang = __tt_lang;

})();
